version: '3'
services:

    kafka1:
        image: my-kafka-ssl:latest
        container_name: kafka1
        build:
         context: .
         dockerfile: Dockerfile.kafka
        restart: always
        hostname: kafka1
        ports:
          - "9091:9093"
        depends_on:
          - zk1
          - zk2
          - zk3
        environment:
          BROKER_ID: 1
          ZK_SERVER: zk1:2181,zk2:2181,zk3:2181
        volumes:
          - ./kafka.properties:/broker/kafka.properties
          - ./secrets/kafka1.truststore.jks:/kafka1/kafka1.truststore.jks
          - ./secrets/kafka1.keystore.jks:/kafka1/kafka1.keystore.jks

    kafka2:
        image: my-kafka-ssl:latest
        container_name: kafka2
        build:
         context: .
         dockerfile: Dockerfile.kafka
        restart: always
        hostname: kafka2
        ports:
          - "9092:9093"
        depends_on:
          - zk1
          - zk2
          - zk3
        environment:
          BROKER_ID: 2
          ZK_SERVER: zk1:2181,zk2:2181,zk3:2181
        volumes:
          - ./kafka.properties:/broker/kafka.properties
          - ./secrets/kafka2.truststore.jks:/kafka2/kafka2.truststore.jks
          - ./secrets/kafka2.keystore.jks:/kafka2/kafka2.keystore.jks

    kafka3:
        image: my-kafka-ssl:latest
        container_name: kafka3
        build:
         context: .
         dockerfile: Dockerfile.kafka
        restart: always
        hostname: kafka3
        ports:
          - "9093:9093"
        depends_on:
          - zk1
          - zk2
          - zk3
        environment:
          BROKER_ID: 3
          ZK_SERVER: zk1:2181,zk2:2181,zk3:2181
        volumes:
          - ./kafka.properties:/broker/kafka.properties
          - ./secrets/kafka3.truststore.jks:/kafka3/kafka3.truststore.jks
          - ./secrets/kafka3.keystore.jks:/kafka3/kafka3.keystore.jks

    kafka-manager:
        image: hlebalbau/kafka-manager:latest
        container_name: kafka-manager
        environment:
          ZK_HOSTS: zk1:2181,zk2:2181,zk3:2181
          APPLICATION_SECRET: "password"
        logging:
          options:
            max-file: "5"
            max-size: "10m"
        ports:
           - "9000:9000"
        depends_on:
          - zk1
          - zk2
          - zk3
